### PR TITLE
Honour path on static middleware

### PR DESCRIPTION
**Pull request by zeloff**
Checks if requested file is inside the bound path.

### CODE REVIEW

**Comment by Bart6114** [comment]
Hi @zeloff, thanks for the PR.

Could you explain to me when/how you encountered issues where `substr(req$path, 2, nchar(path) + 1) == path` was not `True`? I will add testing for these cases.

**Comment by zeloff** [comment]
Hi @Bart6114 
I'm not sure I entirely understand your question, so I apologize if I'm not answering it properly. I issued the PR because I discovered that the `path` argument wasn't being used at all inside the function, only `root_path`.  Having a (working) `path` is nice because it allows me to select which paths inside `root_path` are served and which aren't. In its present form, if `serve_static_files()` is called then all files inside `root_path` are accessible, which might not be desirable.

In the PR the `substr(req$path, 2, nchar(path) + 1) == path` checks that the start of `req$path` matches the path being served.

E.g. take an app served like this:
```
jug %>%
  serve_static_files(path = "A/B") %>%
  serve_it()
```
If a request is made for `http://127.0.0.1:8080/A/B/foo.txt` then the file will be served, because `path = 'A/B'` and `req$path = '/A/B/foo.txt'`, which means that `substr(req$path, 2, nchar(path) + 1) = 'A/B'` which is equal to `path`. So, `bound` becomes `TRUE`and the file is served. However, if a request is made for `http://127.0.0.1:8080/A/foo.txt`, then `subsrt(req$path, 2, nchar(path) + 1) = 'A'` which is _not_ equal to `path` and a 404 is returned.

Another approach can be followed: the `path` argument can be dropped altogether, and multiple calls with different `root_path`s can be used. But I find that makes the relationship between URLs and directories more confusing. Also, if using something like:
```
jug %>%
  serve_static_files(root_path = "E") %>%
  serve_static_files(root_path = "F") %>%
  serve_it()
```
and if both files `E/foo.txt` and `F/foo.txt` exist, then the result of `http://127.0.0.1/foo.txt` would depend on middleware precedence, since both would give valid responses.

**Comment by Bart6114** [comment]
Thanks for the explanation. I've looked a bit closer into this issue.

First to come back to the `path` argument. The `path` argument is simply the path that the middleware will bind to and should do nothing more / less than that.

I think the `serve_static_files` middleware should adhere to the `path` binding plus the serve the files that are located in `root_path` independent of what the value of `path` is. Concretely this would look as follows:

| path | root_path               | req$path       | file served                        |
|------|-------------------------|----------------|------------------------------------|
| NULL | /path/to/files/         | /my_file.txt   | /path/to/files/my_file.txt         |
| /A/  | /path/to/files/         | /A/my_file.txt | /path/to/files/my_file.txt         |
| /A/  | /path/to/files/A_files/ | /A/my_file.txt | /path/to/files/A_files/my_file.txt |

I think this would fix your current issue. Do you agree?
If so I will merge and do a few minor changes to allow this behaviour.

**Comment by zeloff** [comment]
Ah! I see now that I had misunderstood what each argument does. `path` refers to the URL (i.e. to how the file is requested) and `root_path` to the file system.  Things make much more sense now, and I agree with the behaviour you propose.

**Pull request merged**
